
name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libgrpc++-dev protobuf-compiler-grpc libprotobuf-dev libhiredis-dev libprometheus-cpp-dev
      - name: Build
        run: mkdir build && cd build && cmake .. && make -j
      - name: Run tests
        run: echo "ctest placeholder"
